
encode:
  human:
    ab: https://www.encodeproject.org/files/ENCFF745LVW/@@download/ENCFF745LVW.tsv
    talon_filt_ab: https://www.encodeproject.org/files/ENCFF362PTT/@@download/ENCFF362PTT.tsv
    lapa_filt_ab: https://www.encodeproject.org/files/ENCFF677EPK/@@download/ENCFF677EPK.tsv
    lapa_gtf_gz: https://www.encodeproject.org/files/ENCFF298YZW/@@download/ENCFF298YZW.gtf.gz
    filt_ab: https://www.encodeproject.org/files/ENCFF139IUH/@@download/ENCFF139IUH.tsv
    read_annot: https://www.encodeproject.org/files/ENCFF857YZZ/@@download/ENCFF857YZZ.tsv
    new_gencode_gtf_gz: https://www.encodeproject.org/files/ENCFF691CWD/@@download/ENCFF691CWD.gtf.gz
    cerb_gtf_gz: https://www.encodeproject.org/files/ENCFF232ABR/@@download/ENCFF232ABR.gtf.gz
    cerb_annot: https://www.encodeproject.org/files/ENCFF229IBK/@@download/ENCFF229IBK.h5
    gtex_gtf_gz: https://www.encodeproject.org/files/ENCFF652XQK/@@download/ENCFF652XQK.gtf.gz
    fa_gz: https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz
  mouse:
    ab: https://www.encodeproject.org/files/ENCFF811SVZ/@@download/ENCFF811SVZ.tsv
    talon_filt_ab: https://www.encodeproject.org/files/ENCFF961XZJ/@@download/ENCFF961XZJ.tsv
    lapa_filt_ab: https://www.encodeproject.org/files/ENCFF970SFR/@@download/ENCFF970SFR.tsv
    lapa_gtf_gz: https://www.encodeproject.org/files/ENCFF185BAP/@@download/ENCFF185BAP.gtf.gz
    filt_ab: https://www.encodeproject.org/files/ENCFF759BBW/@@download/ENCFF759BBW.tsv
    read_annot: https://www.encodeproject.org/files/ENCFF283TZF/@@download/ENCFF283TZF.tsv
    new_gencode_gtf_gz: https://www.encodeproject.org/files/ENCFF060VNF/@@download/ENCFF060VNF.gtf.gz
    cerb_gtf_gz: https://www.encodeproject.org/files/ENCFF200RSU/@@download/ENCFF200RSU.gtf.gz
    cerb_annot: https://www.encodeproject.org/files/ENCFF999KXH/@@download/ENCFF999KXH.h5
    fa_gz: https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz
  spikes:
    sirv_gtf_gz: https://www.encodeproject.org/files/ENCFF873AAI/@@download/ENCFF873AAI.gtf.gz
    sirv_fa_gz: https://www.encodeproject.org/files/ENCFF473RJX/@@download/ENCFF473RJX.fasta.gz
    ercc_fa_gz: https://www.encodeproject.org/files/ENCFF001RTP/@@download/ENCFF001RTP.fasta.gz

link:
    human:
      p_fa: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_40/gencode.v40.pc_translations.fa.gz
    mouse:
      p_fa: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.pc_translations.fa.gz

sr:
  ab: data/{species}/sr/abundance.tsv
  meta: data/{species}/sr/metadata.tsv

data:
  ab: data/{species}/abundance.tsv
  talon_filt_ab: data/{species}/talon_abundance_filtered.tsv
  lapa_filt_ab: data/{species}/lapa_abundance_filtered.tsv
  lapa_gtf_gz: data/{species}/lapa.gtf.gz
  lapa_gtf: data/{species}/lapa.gtf
  filt_ab: data/{species}/abundance_filtered.tsv
  read_annot: data/{species}/read_annot.tsv
  cerb_gtf_gz: data/{species}/cerberus.gtf.gz
  cerb_gtf: data/{species}/cerberus.gtf
  cerb_annot: data/{species}/cerberus_annot.h5
  t_info: data/{species}/cerberus_t_metadata.tsv
  meta: ref/{species}/lr_{species}_library_data_summary.tsv
  sg: data/{species}/swan_graph.p
  major_isos: data/{species}/{obs_col}_major_isos.tsv
  exp_gene_subset: data/{species}/exp_gids_{obs_col}.tsv
  novelties: data/{species}/transcript_novelties.tsv
  pi_tpm:
    tss: data/{species}/tss_{obs_col}_pi_tpm.tsv
    ic: data/{species}/ic_{obs_col}_pi_tpm.tsv
    tes: data/{species}/tes_{obs_col}_pi_tpm.tsv
    triplet: data/{species}/triplet_{obs_col}_pi_tpm.tsv
  mirna:
    files: data/{species}/mirna/files.txt
    lib_meta: data/{species}/mirna/mirna_{species}_library_data_summary.tsv
    meta: data/{species}/mirna/metadata.tsv
    tsv: data/{species}/mirna/{encid}.tsv
  psi: data/{species}/cerberus_psi.tsv
  suppa:
    gtf: data/{species}/suppa/cerberus_filtered.gtf
    filt_ab: data/{species}/suppa/cerberus_filtered_abundance.tsv
    events:
      A3: data/{species}/suppa/cerberus.events_A3_strict.ioe
      A5: data/{species}/suppa/cerberus.events_A5_strict.ioe
      AF: data/{species}/suppa/cerberus.events_AF_strict.ioe
      AL: data/{species}/suppa/cerberus.events_AL_strict.ioe
      MX: data/{species}/suppa/cerberus.events_MX_strict.ioe
      RI: data/{species}/suppa/cerberus.events_RI_strict.ioe
      SE: data/{species}/suppa/cerberus.events_SE_strict.ioe
    psi: data/{species}/suppa/psi/cerb_{event}.psi
    gtex:
      events:
        A3: data/{species}/suppa/gtex/cerberus.events_A3_strict.ioe
        A5: data/{species}/suppa/gtex/cerberus.events_A5_strict.ioe
        AF: data/{species}/suppa/gtex/cerberus.events_AF_strict.ioe
        AL: data/{species}/suppa/gtex/cerberus.events_AL_strict.ioe
        MX: data/{species}/suppa/gtex/cerberus.events_MX_strict.ioe
        RI: data/{species}/suppa/gtex/cerberus.events_RI_strict.ioe
        SE: data/{species}/suppa/gtex/cerberus.events_SE_strict.ioe
      psi: data/{species}/suppa/gtex/psi/gtex_{event}.psi
      cerb_ids: data/{species}/suppa/gtex/cerb_ids.tsv
    matching_events: data/{species}/suppa/{event}_combined.tsv
  bam: data/{species}/bam/{encid}.bam
  fastq_gz: data/{species}/fastq/{encid}.fastq.gz
  read_len_meta: data/{species}/lr_bulk_read_length_meta.tsv
  p_pred:
    gtf_bed: data/{species}/protein_pred/{species}_tama.bed
    fa: data/{species}/protein_pred/{species}.fa
    orf_fa: data/{species}/protein_pred/{species}_orf.fa
    blastp: data/{species}/protein_pred/{species}_blastp.out
    blastp_6: data/{species}/protein_pred/{species}_blastp.6.out
    blastp_parsed: data/{species}/protein_pred/{species}_blastp.tsv
    cds_bed: data/{species}/protein_pred/{species}_cds.bed
    summary: data/{species}/protein_pred/{species}_summary.tsv
  spike:
    bam: data/{species}/bam/{encid}_spike.bam


tama_dir: ~/mortazavi_lab/bin/tama/tama_go/


# this will be vM21 for mouse and v40 for human
ref:
  gtex_gtf_gz: ref/{species}/gtex.gtf.gz
  gtex_gtf: ref/{species}/gtex.gtf
  fa_gz: ref/{species}/genome.fa.gz
  fa: ref/{species}/genome.fa
  new_gencode_gtf_gz: ref/{species}/gencode_annotation.gtf.gz
  new_gencode_gtf: ref/{species}/gencode_annotation.gtf
  p_fa_gz: ref/{species}/gencode_protein.fa.gz
  p_fa: ref/{species}/gencode_protein.fa
  p_fa_header: ref/{species}/gencode_protein_short_headers.fa
  p_db: ref/{species}/gencode_protein_translations.pdb
  t_info: ref/{species}/gencode_t_metadata.tsv
  g_info: ref/{species}/gencode_g_metadata.tsv
  cerberus:
    gtf: ref/{species}/cerberus/cerberus.gtf
    t_info: ref/{species}/cerberus/cerberus_t_metadata.tsv
    g_info: ref/{species}/cerberus/cerberus_g_metadata.tsv
  spikes:
    sirv_gtf_gz: ref/spikes/sirv4.gtf.gz
    sirv_gtf: ref/spikes/sirv4.gtf
    sirv_fa_gz: ref/spikes/sirv4.fa.gz
    sirv_fa: ref/spikes/sirv4.fa

    ercc_fa_gz: ref/spikes/ercc.fa.gz
    ercc_fa: ref/spikes/ercc.fa
    ercc_gtf: ref/spikes/ercc.gtf

    spike_gtf: ref/spikes/spikes.gtf
    spike_fa: ref/spikes/spikes.fa

    chrom_sizes: ref/spikes/chrom_sizes.fa
    chrom_bed: ref/spikes/chroms.bed
