params:
  talon:
    datasets_per_run: 14
    min_transcript_len: 0
    int_priming_a_range: 20
    max_5_dist: 500
    max_3_dist: 300
    max_frac_a: 0.5
    min_count: 5
    min_datasets: 2

  cerberus:
    tss:
      dist: 50
      slack: 50
      agg_slack: 20
    tes:
      dist: 50
      slack: 50
      agg_slack: 20

ref:
  # links to download
  human:
    gtf_ver: 'v29'
    gtf_link: https://www.encodeproject.org/files/gencode.v29.primary_assembly.annotation_UCSC_names/@@download/gencode.v29.primary_assembly.annotation_UCSC_names.gtf.gz
    new_gtf_ver: 'v40'
    new_gtf_link: https://www.encodeproject.org/files/ENCFF691CWD/@@download/ENCFF691CWD.gtf.gz
    fa_ver: 'hg38'
    fa_link: https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz
    chrom_sizes_link: https://www.encodeproject.org/files/ENCFF667IGK/@@download/ENCFF667IGK.tsv
  mouse:
    gtf_ver: 'vM21'
    gtf_link: https://www.encodeproject.org/files/gencode.vM21.primary_assembly.annotation_UCSC_names/@@download/gencode.vM21.primary_assembly.annotation_UCSC_names.gtf.gz
    new_gtf_ver: 'vM25'
    new_gtf_link: https://www.encodeproject.org/files/ENCFF060VNF/@@download/ENCFF060VNF.gtf.gz
    fa_ver: 'mm10'
    fa_link: https://www.encodeproject.org/files/mm10_no_alt_analysis_set_ENCODE/@@download/mm10_no_alt_analysis_set_ENCODE.fasta.gz

  # links and locations of spikes
  spike:
    sirv_gtf_link: https://www.encodeproject.org/files/ENCFF873AAI/@@download/ENCFF873AAI.gtf.gz
    sirv_gtf_gz: ref/spike/sirv.gtf.gz
    sirv_gtf: ref/spike/sirv.gtf
    sirv_fa_link: https://www.encodeproject.org/files/ENCFF473RJX/@@download/ENCFF473RJX.fasta.gz
    sirv_fa_gz: ref/spike/sirv.fa.gz
    sirv_fa: ref/spike/sirv.fa
    ercc_gtf: ref/spike/ercc.gtf
    ercc_fa_link: https://www.encodeproject.org/files/ENCFF001RTP/@@download/ENCFF001RTP.fasta.gz
    ercc_fa_gz: ref/spike/ercc.fa.gz
    ercc_fa: ref/spike/ercc.fa


  # vM21 or v29
  gtf_gz: ref/{species}/annot.gtf.gz
  gtf: ref/{species}/annot.gtf

  # vM25 or v40
  new_gtf_gz: ref/{species}/new_annot.gtf.gz
  new_gtf: ref/{species}/new_annot.gtf

  fa_gz: ref/{species}/ref.fa.gz
  fa: ref/{species}/ref.fa

  # TALON reference - ENCODE refs (vM21 or v29) + SIRV + ERCC
  talon:
    fa: ref/{species}/talon/ref.fa
    chrom_sizes: ref/{species}/talon/ref_chrom_sizes.txt
    gtf: ref/{species}/talon/ref.gtf

  # LAPA reference - ENCODE refs (vM21 or v29) + SIRV + ERCC + GENCODE UTRs
  lapa:
    gtf: ref/{species}/lapa/ref.gtf

  # Cerberus reference - ICs, ends from each annotation
  cerberus:
    ics: ref/{species}/cerberus/ics.tsv
    ends: ref/{species}/cerberus/{end_mode}.bed
    new_ics: ref/{species}/cerberus/new_ics.tsv
    new_ends: ref/{species}/cerberus/new_{end_mode}.bed

ccre:
  bed_gz: data/{species}/ccre/{ccre_type}.bed.gz
  bed: data/{species}/ccre/{ccre_type}.bed
  bed_format: data/{species}/ccre/{ccre_type}_formatted.bed

lr:
  meta: data/{species}/lr/lr_{species}_library_data_summary.tsv
  encode_meta: data/{species}/lr/encode_metadata.tsv
  bam: data/{species}/lr/tc/{dataset}.bam

  talon:
    sam_label: data/{species}/lr/talon/label/{dataset}_labeled.sam
    read_labels: data/{species}/lr/talon/label/{dataset}_read_labels.tsv

    bam: data/{species}/lr/talon/label/{dataset}.bam
    bam_sort: data/{species}/lr/talon/label/{dataset}_sorted.bam
    bam_ind: data/{species}/lr/talon/label/{dataset}_sorted.bam.bai

    ref_db: data/{species}/lr/talon/ref/ref.db

    config: data/{species}/lr/talon/{talon_run}_config.csv
    db: data/{species}/lr/talon/{talon_run}_talon.db
    annot: data/{species}/lr/talon/{talon_run}_talon_read_annot.tsv
    temp_dir: data/{species}/lr/talon/{talon_run}_temp/

    full_annot: data/{species}/lr/talon/full_talon_read_annot.tsv
    pass_list: data/{species}/lr/talon/talon_pass_list.csv
    ab: data/{species}/lr/talon/unfilt_talon_abundance.tsv
    filt_ab: data/{species}/lr/talon/talon/filt_talon_abundance_filtered.tsv
    gtf: data/{species}/lr/talon/annot_talon.gtf


  lapa:
    config: data/{species}/lr/lapa/config.csv
    ends: data/{species}/lr/lapa/{end_mode}/{end_mode}_clusters.bed
    links: data/{species}/lr/lapa/tss_to_tes_links.csv

    gtf: data/{species}/lr/lapa/lapa_corrected.gtf
    filt_ab: data/{species}/lr/lapa/lapa_corrected_filtered_abundance.tsv

    filt:
      pass_list: data/{species}/lr/lapa/filt/lapa_pass_list.tsv
      filt_ab: data/{species}/lr/lapa/filt/lapa_corrected_filtered_abundance.tsv
      gtf: data/{species}/lr/lapa/filt/lapa_corrected.gtf

  cerberus:
    ics: data/{species}/lr/cerberus/ics.tsv
    ends: data/{species}/lr/cerberus/{end_mode}.bed
    ca: data/{species}/lr/cerberus/cerberus_ref.h5
    ca_annot: data/{species}/lr/cerberus/cerberus_annot.h5
    gtf: data/{species}/lr/cerberus/cerberus.gtf
    ab: data/{species}/lr/cerberus/cerberus_filtered_abundance.tsv

gtex:
    gtf_link: https://storage.googleapis.com/gtex_analysis_v9/long_read_data/flair_filter_transcripts.gtf.gz
    gtf_gz: data/human/gtex/flair_filter_transcripts.gtf.gz
    gtf: data/human/gtex/flair_filter_transcripts.gtf
    filt_gtf: data/human/gtex/flair_filter_transcripts_no_novel_genes.gtf

    cerberus:
      ics: data/human/gtex/cerberus/ics.tsv
      ends: data/human/gtex/cerberus/{end_mode}.bed
      annot: data/human/gtex/cerberus/gtex_cerberus.h5

cage:
  encode_meta: data/{species}/cage/encode_metadata.tsv
  bed_gz: data/{species}/cage/{encid}.bed.gz
  bed: data/{species}/cage/{encid}.bed
  merged: data/{species}/cage/merged.bed

rampage:
  encode_meta: data/{species}/rampage/encode_metadata.tsv
  bed_gz: data/{species}/rampage/{encid}.bed.gz
  bed: data/{species}/rampage/{encid}.bed
  merged: data/{species}/rampage/merged.bed

fantom:
  human:
    link: https://fantom.gsc.riken.jp/5/datafiles/latest/extra/CAGE_peaks/hg19.cage_peak_phase1and2combined_coord.bed.gz
  mouse:
    link: https://fantom.gsc.riken.jp/5/datafiles/latest/extra/CAGE_peaks/mm9.cage_peak_phase1and2combined_coord.bed.gz
  bed_old_gz: data/{species}/fantom_cage/old.bed.gz
  bed_old: data/{species}/fantom_cage/old.bed
  bed: data/{species}/fantom_cage/fantom_cage.bed

lrgasp_cage:
    metadata: data/{species}/lrgasp_cage/metadata.tsv
    bed_gz: data/{species}/lrgasp_cage/{lrgasp_cage_dataset}.bed.gz
    bed: data/{species}/lrgasp_cage/{lrgasp_cage_dataset}.bed
    merged: data/{species}/lrgasp_cage/merged.bed


polya_atlas:
  human:
    link: https://www.polyasite.unibas.ch/download/atlas/2.0/GRCh38.96/atlas.clusters.2.0.GRCh38.96.bed.gz
  mouse:
    link: https://www.polyasite.unibas.ch/download/atlas/2.0/GRCm38.96/atlas.clusters.2.0.GRCm38.96.bed.gz
  bed_gz: data/{species}/polyasite_atlas/polyasite.bed.gz
  bed: data/{species}/polyasite_atlas/polyasite.bed
  bed_formatted: data/{species}/polyasite_atlas/polyasite_formatted.bed

pas:
  encode_meta: data/{species}/pas/encode_metadata.tsv
  bam: data/{species}/pas/{encid}.bam
  config: data/{species}/pas/lapa/config.csv
  ends: data/{species}/pas/lapa/{end_mode}/{end_mode}_clusters.bed
  ends_formatted: data/{species}/pas/lapa/{end_mode}/{end_mode}_clusters_formatted.bed
