ref:
  mm10:
    fa: ~/mortazavi_lab/ref/mm10/mm10_sirv4.fasta
  vM25:
    link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.annotation.gtf.gz
    gz: refs/gencode_vM25.gtf.gz
    gtf: refs/gencode_vM25.gtf
    cerberus:
      annot: refs/cerberus/vM25_cerberus.h5
      gtf: refs/cerberus/vM25_cerberus.gtf
      t_info: refs/cerberus/vM25_transcript_metadata.tsv
      g_info: refs/cerberus/vM25_gene_metadata.tsv
  vM21:
    link: https://www.encodeproject.org/files/gencode.vM21.primary_assembly.annotation_UCSC_names/@@download/gencode.vM21.primary_assembly.annotation_UCSC_names.gtf.gz
    gz: refs/gencode_vM21.gtf.gz
    gtf: refs/gencode_vM21.gtf
    cerberus:
      annot: refs/cerberus/vM21_cerberus.h5
      gtf: refs/cerberus/vM21_cerberus.gtf
      t_info: refs/cerberus/vM21_transcript_metadata.tsv
  tf:
    gid: refs/biomart_tf_gids.tsv

lapa:

    hasan_gtf: /share/crsp/lab/seyedam/share/mousewg/data/results/talon_corrected/mouse_talon.corrected.gtf
    hasan_ab: /share/crsp/lab/seyedam/share/mousewg/data/results/talon_corrected/mouse_talon_abundance_filtered.corrected.tsv
    # hasan_gtf: /dfs7/samlab/mcelik/mousewg/data/results/talon_corrected/mouse_talon.corrected.gtf
    # hasan_ab: /dfs7/samlab/mcelik/mousewg/data/results/talon_corrected/mouse_talon_abundance_filtered.corrected.tsv

    # corrected output right from lapa
    gtf: mouse/lr_bulk/lapa/mouse_talon.corrected.gtf
    ab: mouse/lr_bulk/lapa/mouse_talon_abundance_filtered.corrected.tsv

    # output with ISM_rescue category added
    nov_ab: mouse/lr_bulk/lapa/mouse_talon_abundance_filtered.nov_corrected.tsv
    nov_gtf: mouse/lr_bulk/lapa/mouse_talon.nov_corrected.gtf

    # output filtered for the relevant novelty categories
    filt_ab: mouse/lr_bulk/lapa/mouse_abundance_filtered.tsv
    filt_gtf: mouse/lr_bulk/lapa/mouse_lapa.gtf

    # tss / tes clusters from lapa
    # these have been updated and I didn't use them but it didn't matter
    # because these are not used downstream
    tss: /share/crsp/lab/seyedam/share/mousewg/data/results/lapa/tss/tss_clusters.bed
    tes: /share/crsp/lab/seyedam/share/mousewg/data/results/lapa/tes/polyA_clusters.bed

raw:
  bam: mouse/lr_bulk/processing/{sample}.bam

meta:
  file_to_hr: mouse/lr_bulk/file_to_hr.tsv
  meta: mouse/lr_bulk/metadata.tsv

talon:
  prefix: mouse/lr_bulk/talon/mouse
  sam: mouse/lr_bulk/processing/{sample}_labeled.sam
  cfg_6: mouse/lr_bulk/talon/talon_config_6.csv
  db: mouse/lr_bulk/talon/mouse.db
  db_update: mouse/lr_bulk/talon/talon_update.db
  read_annot: mouse/lr_bulk/talon/mouse_talon_read_annot.tsv
  ab: mouse/lr_bulk/talon/mouse_talon_abundance.tsv
  gene_ab: mouse/lr_bulk/talon/mouse_talon_gene_abundance.tsv
  pass_list: mouse/lr_bulk/talon/mouse_pass_list.csv
  filt_ab: mouse/lr_bulk/talon/mouse_talon_abundance_filtered.tsv
  filt_gtf: mouse/lr_bulk/talon/mouse_talon.gtf
  known_novel_pass_list: mouse/lr_bulk/talon/mouse_vM21_novel_pass_list.csv
  known_novel_gtf: mouse/lr_bulk/talon/mouse_vM21_novel_talon.gtf
  known_nic_nnc_pass_list: mouse/lr_bulk/talon/mouse_known_nic_nnc_pass_list.csv
  known_nic_nnc_gtf: mouse/lr_bulk/talon/mouse_known_nic_nnc_talon.gtf

polyasite_atlas:
  original: /dfs7/samlab/mcelik/mousewg/data/resources/polyasite_atlas/atlas.clusters.2.0.GRCm38.96.bed
  formatted: /dfs7/samlab/mcelik/mousewg/data/resources/polyasite_atlas/atlas.clusters_formatted.bed

fantom:
  mm9: /dfs7/samlab/mcelik/mousewg/data/resources/fantom/mm9.cage_peak_phase1and2combined_coord.bed

cCREs:
  promoters: /dfs7/samlab/mcelik/mousewg/data/resources/cCREs/mm10-PLS.bed
  proximal_enhancers: /dfs7/samlab/mcelik/mousewg/data/resources/cCREs/mm10-ccREs.pELS.bed
  distal_enhancers: /dfs7/samlab/mcelik/mousewg/data/resources/cCREs/mm10-ccREs.dELS.bed

cerberus:
  gtf:
    ends: mouse/lr_bulk/cerberus/{source}_{mode}.bed
    ics: mouse/lr_bulk/cerberus/{source}_ics.tsv
  tss:
    lapa: mouse/lr_bulk/lapa/lapa_tss.bed
    cfg: mouse/lr_bulk/cerberus/agg_tss_config.csv
    agg: mouse/lr_bulk/cerberus/agg_tss.bed
    source_map: mouse/lr_bulk/cerberus/agg_tss_source_map.bed
  tes:
    lapa: mouse/lr_bulk/lapa/lapa_tes.bed
    pas: mouse/lr_bulk/lapa/pas_tes.bed
    cfg: mouse/lr_bulk/cerberus/agg_tes_config.csv
    agg: mouse/lr_bulk/cerberus/agg_tes.bed
    source_map: mouse/lr_bulk/cerberus/agg_tes_source_map.bed
  ics:
    cfg: mouse/lr_bulk/cerberus/agg_ics_config.csv
    agg: mouse/lr_bulk/cerberus/agg_ics.tsv
  ref: mouse/lr_bulk/cerberus/cerberus_ref.h5 # does not contain full transcripts
  annot: mouse/lr_bulk/cerberus/cerberus_annot.h5 # does contain full transcripts
  update_ab: mouse/lr_bulk/cerberus/cerberus_filtered_abundance.tsv
  update_gtf: mouse/lr_bulk/cerberus/cerberus.gtf

swan:
  sg: mouse/lr_bulk/swan/swan.p
  die: mouse/lr_bulk/swan/die/{tissue}_{cond1}_{cond2}_{gb}_{kind}_die.tsv
  die_all: 'temp.tsv'
  sg_unfilt: 'mouse/lr_bulk/swan/swan.p'
  meta: 'mouse/lr_bulk/swan/mouse_metadata.tsv'
